services:
  main-service:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    env_file:
      - ./backend/.env

  auth-service:
    build:
      context: ./auth-service
    volumes:
      - ./auth-service:/app
      - go-modules2:/go/pkg/mod
    env_file:
      - ./auth-service/.env
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - main-service
      - auth-service

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - '15672:15672'
    env_file:
      - ./rabbitmq/.env
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

volumes:
  go-modules:
  go-modules2:
