services:
  main-service:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    env_file:
      - ./backend/.env

  auth-service:
    build:
      context: ./auth-service
    ports:
      - '8081:8081'
    volumes:
      - ./auth-service:/app
      - go-modules2:/go/pkg/mod
    env_file:
      - ./auth-service/.env

volumes:
  go-modules:
  go-modules2:
